# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from greet.v1 import greet_pb2 as greet_dot_v1_dot_greet__pb2


class GreetServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Greet = channel.unary_unary(
                '/greet.v1.GreetService/Greet',
                request_serializer=greet_dot_v1_dot_greet__pb2.GreetRequest.SerializeToString,
                response_deserializer=greet_dot_v1_dot_greet__pb2.GreetResponse.FromString,
                _registered_method=True)
        self.GreetStream = channel.unary_stream(
                '/greet.v1.GreetService/GreetStream',
                request_serializer=greet_dot_v1_dot_greet__pb2.GreetRequest.SerializeToString,
                response_deserializer=greet_dot_v1_dot_greet__pb2.GreetResponse.FromString,
                _registered_method=True)


class GreetServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Greet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GreetStream(self, request, context):
        """New streaming RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Greet': grpc.unary_unary_rpc_method_handler(
                    servicer.Greet,
                    request_deserializer=greet_dot_v1_dot_greet__pb2.GreetRequest.FromString,
                    response_serializer=greet_dot_v1_dot_greet__pb2.GreetResponse.SerializeToString,
            ),
            'GreetStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GreetStream,
                    request_deserializer=greet_dot_v1_dot_greet__pb2.GreetRequest.FromString,
                    response_serializer=greet_dot_v1_dot_greet__pb2.GreetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greet.v1.GreetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('greet.v1.GreetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GreetService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Greet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/greet.v1.GreetService/Greet',
            greet_dot_v1_dot_greet__pb2.GreetRequest.SerializeToString,
            greet_dot_v1_dot_greet__pb2.GreetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GreetStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/greet.v1.GreetService/GreetStream',
            greet_dot_v1_dot_greet__pb2.GreetRequest.SerializeToString,
            greet_dot_v1_dot_greet__pb2.GreetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
